pushinf scan changes

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -108,10 +108,13 @@ jobs:
           qualityGateStatus=$(echo "$qualityGateResponse" | jq -r '.projectStatus.status')
           echo "Quality Gate Status: $qualityGateStatus"
 
-          if [ "$qualityGateStatus" == "ERROR" ]; then
-            echo "Quality Gate failed, but continuing the pipeline."
-          else
+          if [ "$qualityGateStatus" == "OK" ]; then
             echo "Quality Gate passed!"
+            exit 0
+          else
+            echo "Quality Gate failed!"
+            exit 1
           fi
+
 
 
