test tag 1.8 main

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -70,6 +70,8 @@ jobs:
         echo "PACKAGE_ID: $PACKAGE_ID"
         echo "PACKAGE_VERSION: $PACKAGE_VERSION"
 
+        
+
     - name: Pack packages
       run: |
         dotnet pack --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }} \
@@ -77,6 +79,13 @@ jobs:
           /p:PackageVersion=$PACKAGE_VERSION
         ARTIFACT_PATH="${{ env.PACKAGE_OUTPUT_DIR }}/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg"
         echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
+        echo "Packaging completed. Artifact path: $ARTIFACT_PATH"
+
+        if [ ! -f "${ARTIFACT_PATH}" ]; then
+          echo "Error: Package file not found at ${ARTIFACT_PATH}."
+          exit 1
+        fi
+
 
     - name: Upload Package as Artifact
       uses: actions/upload-artifact@v3
